const fs = require('fs');

const rawData = [
  {
    "name": "Tomato",
    "variety": "Cherry",
    "type": "Vegetable",
    "scientific_name": "Solanum lycopersicum",
    "source": "Nursery seedling",
    "days_to_maturity": 70,
    "height_cm": 120,
    "water_need": "High",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "6.0-6.8",
    "soil_amendment": "Compost + cow dung",
    "sow_method": "Nursery bed",
    "spacing_cm": 45,
    "germination_days": 7,
    "growing_method": "Container",
    "growing_notes": "Ideal in 12-inch pots. Use cage or trellis for support. Excellent balcony crop.",
    "care_notes": "Pinch suckers; stake at 30cm. Neem oil for aphids.",
    "harvest_season": "June-September",
    "yield_unit": "kg",
    "common_pests": "Aphids, whitefly",
    "fertilizer": "NPK 10-10-10 monthly"
  },
  {
    "name": "Hot Pepper",
    "variety": "Jalapeno",
    "type": "Vegetable",
    "scientific_name": "Capsicum annuum",
    "source": "Nursery seedling",
    "days_to_maturity": 80,
    "height_cm": 60,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "6.0-6.8",
    "soil_amendment": "Compost",
    "sow_method": "Nursery bed",
    "spacing_cm": 40,
    "germination_days": 10,
    "growing_method": "Both",
    "growing_notes": "Thrives in containers (10-inch) or ground bed. Great for terrace gardens.",
    "care_notes": "Pinch terminal buds at 25cm. Water early morning.",
    "harvest_season": "July-October",
    "yield_unit": "kg",
    "common_pests": "Thrips, mites",
    "fertilizer": "Potash-rich after flowering"
  },
  {
    "name": "Brinjal",
    "variety": "Round Purple",
    "type": "Vegetable",
    "scientific_name": "Solanum melongena",
    "source": "Local nursery",
    "days_to_maturity": 75,
    "height_cm": 90,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "5.5-6.5",
    "soil_amendment": "Farmyard manure",
    "sow_method": "Nursery bed",
    "spacing_cm": 60,
    "germination_days": 8,
    "growing_method": "Both",
    "growing_notes": "Ground bed preferred for full yield. Can be container-grown in 15-inch pots.",
    "care_notes": "Susceptible to shoot borer. Use pheromone traps.",
    "harvest_season": "Year-round",
    "yield_unit": "kg",
    "common_pests": "Shoot and fruit borer",
    "fertilizer": "FYM + urea"
  },
  {
    "name": "Okra",
    "variety": "Arka Anamika",
    "type": "Vegetable",
    "scientific_name": "Abelmoschus esculentus",
    "source": "IIHR",
    "days_to_maturity": 55,
    "height_cm": 150,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 30,
    "germination_days": 5,
    "growing_method": "Ground",
    "growing_notes": "Best in raised ground beds due to height. Can be sown in large grow bags.",
    "care_notes": "Harvest every 2 days to keep producing. Karnataka favourite.",
    "harvest_season": "June-September",
    "yield_unit": "kg",
    "common_pests": "Jassid, yellow mosaic virus",
    "fertilizer": "Urea side-dress at 30 days"
  },
  {
    "name": "Spinach",
    "variety": "Palak",
    "type": "Vegetable",
    "scientific_name": "Spinacia oleracea",
    "source": "Local market seed",
    "days_to_maturity": 35,
    "height_cm": 30,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 15,
    "germination_days": 4,
    "growing_method": "Container",
    "growing_notes": "Perfect window box or container crop. Use shallow 8-inch pots. Great for beginners.",
    "care_notes": "Cut-and-come-again. Bolt-prone in heat.",
    "harvest_season": "Nov-Feb",
    "yield_unit": "bunches",
    "common_pests": "Leaf miner",
    "fertilizer": "Nitrogen-heavy compost"
  },
  {
    "name": "Coriander",
    "variety": "Local",
    "type": "Herb",
    "scientific_name": "Coriandrum sativum",
    "source": "Kitchen seeds",
    "days_to_maturity": 40,
    "height_cm": 45,
    "water_need": "Low",
    "sun_hours": 5,
    "soil_type": "Loamy",
    "soil_ph": "6.2-6.8",
    "soil_amendment": "Light compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 10,
    "germination_days": 7,
    "growing_method": "Container",
    "growing_notes": "Ideal kitchen windowsill herb. Sow densely in shallow trays. Succession sow every 2 weeks.",
    "care_notes": "Sow Oct-Feb in Karnataka. Bolt in summer.",
    "harvest_season": "Nov-March",
    "yield_unit": "bunches",
    "common_pests": "Aphids",
    "fertilizer": "Minimal — compost only"
  },
  {
    "name": "Mint",
    "variety": "Spearmint",
    "type": "Herb",
    "scientific_name": "Mentha spicata",
    "source": "Stem cutting",
    "days_to_maturity": 30,
    "height_cm": 40,
    "water_need": "High",
    "sun_hours": 5,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Cutting",
    "spacing_cm": 20,
    "germination_days": 0,
    "growing_method": "Container",
    "growing_notes": "Must be grown in containers to prevent spreading. Can also grow in water jars.",
    "care_notes": "Grows aggressively — contain in pots. Repels pests.",
    "harvest_season": "Year-round",
    "yield_unit": "bunches",
    "common_pests": "Spider mite",
    "fertilizer": "Liquid seaweed monthly"
  },
  {
    "name": "Curry Leaf",
    "variety": "Regular",
    "type": "Herb",
    "scientific_name": "Murraya koenigii",
    "source": "Local nursery",
    "days_to_maturity": 365,
    "height_cm": 200,
    "water_need": "Low",
    "sun_hours": 6,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Cow dung",
    "sow_method": "Seedling",
    "spacing_cm": 90,
    "germination_days": 21,
    "growing_method": "Both",
    "growing_notes": "Small trees grow well in large pots (18-inch+). Ground gives better yield. Common in every Karnataka home.",
    "care_notes": "Drought tolerant once established. Prune to encourage bushiness.",
    "harvest_season": "Year-round",
    "yield_unit": "sprigs",
    "common_pests": "Psyllid",
    "fertilizer": "Cow dung annually"
  },
  {
    "name": "Tulsi",
    "variety": "Krishna Tulsi",
    "type": "Herb",
    "scientific_name": "Ocimum tenuiflorum",
    "source": "Local nursery",
    "days_to_maturity": 60,
    "height_cm": 60,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 30,
    "germination_days": 7,
    "growing_method": "Container",
    "growing_notes": "Traditional pot plant in Karnataka. 10-inch earthen pots preferred. Place near entrance.",
    "care_notes": "Sacred plant. Pinch flowers to extend leaf production.",
    "harvest_season": "Year-round",
    "yield_unit": "sprigs",
    "common_pests": "Root rot in waterlogged soil",
    "fertilizer": "Light compost"
  },
  {
    "name": "Lemon Grass",
    "variety": "East Indian",
    "type": "Herb",
    "scientific_name": "Cymbopogon citratus",
    "source": "Division",
    "days_to_maturity": 90,
    "height_cm": 120,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Sandy loam",
    "soil_ph": "5.5-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Clump division",
    "spacing_cm": 60,
    "germination_days": 0,
    "growing_method": "Both",
    "growing_notes": "Clump-forming grass. Use large 14-inch containers or ground border beds.",
    "care_notes": "Drought-hardy. Cut to 15cm after each harvest.",
    "harvest_season": "Year-round",
    "yield_unit": "stalks",
    "common_pests": "Minimal",
    "fertilizer": "NPK 6 months"
  },
  {
    "name": "Basil",
    "variety": "Sweet Basil",
    "type": "Herb",
    "scientific_name": "Ocimum basilicum",
    "source": "Seeds",
    "days_to_maturity": 50,
    "height_cm": 45,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Nursery bed",
    "spacing_cm": 25,
    "germination_days": 5,
    "growing_method": "Container",
    "growing_notes": "Classic kitchen container herb. 8-inch pots work well. Pair with tomato containers.",
    "care_notes": "Pinch flower buds to prolong harvest.",
    "harvest_season": "Oct-March",
    "yield_unit": "sprigs",
    "common_pests": "Aphids, whitefly",
    "fertilizer": "Balanced NPK monthly"
  },
  {
    "name": "Fenugreek",
    "variety": "Methi",
    "type": "Herb",
    "scientific_name": "Trigonella foenum-graecum",
    "source": "Kitchen seeds",
    "days_to_maturity": 25,
    "height_cm": 30,
    "water_need": "Low",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 10,
    "germination_days": 3,
    "growing_method": "Container",
    "growing_notes": "Excellent microgreens or full-leaf container crop. Shallow trays or window boxes.",
    "care_notes": "Very fast growing. Leaves used young.",
    "harvest_season": "Oct-Feb",
    "yield_unit": "bunches",
    "common_pests": "Minimal",
    "fertilizer": "None needed"
  },
  {
    "name": "Drumstick",
    "variety": "PKM-1",
    "type": "Vegetable",
    "scientific_name": "Moringa oleifera",
    "source": "Seeds",
    "days_to_maturity": 180,
    "height_cm": 400,
    "water_need": "Low",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "6.3-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 300,
    "germination_days": 7,
    "growing_method": "Ground",
    "growing_notes": "Requires open ground planting. Grows into a large tree — ideal for backyard or community garden.",
    "care_notes": "Karnataka staple. Prune to 1m after first harvest. Highly nutritious.",
    "harvest_season": "Year-round",
    "yield_unit": "pods",
    "common_pests": "Caterpillars",
    "fertilizer": "FYM annually"
  },
  {
    "name": "Banana",
    "variety": "Nendran",
    "type": "Fruit",
    "scientific_name": "Musa paradisiaca",
    "source": "Sucker",
    "days_to_maturity": 300,
    "height_cm": 350,
    "water_need": "High",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "5.5-6.5",
    "soil_amendment": "Compost + potash",
    "sow_method": "Sucker transplant",
    "spacing_cm": 180,
    "germination_days": 0,
    "growing_method": "Ground",
    "growing_notes": "Needs large open ground. Plant in clusters of 3 for better pollination and wind support.",
    "care_notes": "Remove all but 1 sucker. Prop trunk when fruiting.",
    "harvest_season": "Perennial",
    "yield_unit": "bunch",
    "common_pests": "Panama wilt, weevil",
    "fertilizer": "Heavy feeder — compost + potash"
  },
  {
    "name": "Papaya",
    "variety": "Red Lady",
    "type": "Fruit",
    "scientific_name": "Carica papaya",
    "source": "Seeds",
    "days_to_maturity": 270,
    "height_cm": 300,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "FYM",
    "sow_method": "Nursery",
    "spacing_cm": 200,
    "germination_days": 14,
    "growing_method": "Ground",
    "growing_notes": "Ground planting only. Fast-growing — good for small backyards. Avoid water stagnation areas.",
    "care_notes": "Plant 3 seeds per hole — thin to one. Avoid waterlogging.",
    "harvest_season": "Year-round",
    "yield_unit": "fruits",
    "common_pests": "Papaya mealy bug",
    "fertilizer": "NPK + micronutrients"
  },
  {
    "name": "Lemon",
    "variety": "Eureka",
    "type": "Fruit",
    "scientific_name": "Citrus limon",
    "source": "Nursery graft",
    "days_to_maturity": 730,
    "height_cm": 250,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "5.5-6.5",
    "soil_amendment": "Compost",
    "sow_method": "Grafted seedling",
    "spacing_cm": 300,
    "germination_days": 0,
    "growing_method": "Both",
    "growing_notes": "Dwarf grafts thrive in large 18-inch containers on terraces. Ground-planted trees give higher yield.",
    "care_notes": "Annual pruning. Watch for citrus leaf miner.",
    "harvest_season": "Dec-Feb",
    "yield_unit": "fruits",
    "common_pests": "Citrus leaf miner, scale",
    "fertilizer": "Citrus-specific NPK"
  },
  {
    "name": "Guava",
    "variety": "Allahabad Safeda",
    "type": "Fruit",
    "scientific_name": "Psidium guajava",
    "source": "Nursery",
    "days_to_maturity": 730,
    "height_cm": 400,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Any",
    "soil_ph": "5.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Seedling",
    "spacing_cm": 400,
    "germination_days": 0,
    "growing_method": "Ground",
    "growing_notes": "Open ground required. Excellent drought-tolerant backyard tree for Karnataka.",
    "care_notes": "Drought tolerant. Prune after harvest.",
    "harvest_season": "June-August",
    "yield_unit": "kg",
    "common_pests": "Fruit fly",
    "fertilizer": "Moderate compost"
  },
  {
    "name": "Chikoo",
    "variety": "Cricket Ball",
    "type": "Fruit",
    "scientific_name": "Manilkara zapota",
    "source": "Nursery graft",
    "days_to_maturity": 1095,
    "height_cm": 600,
    "water_need": "Low",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-8.0",
    "soil_amendment": "FYM",
    "sow_method": "Grafted seedling",
    "spacing_cm": 600,
    "germination_days": 0,
    "growing_method": "Ground",
    "growing_notes": "Large tree — needs open ground and plenty of space. Long-term investment crop.",
    "care_notes": "Very drought hardy once established. Long lived tree.",
    "harvest_season": "Nov-Jan",
    "yield_unit": "fruits",
    "common_pests": "Bud borer",
    "fertilizer": "Annual FYM"
  },
  {
    "name": "Coconut",
    "variety": "Tiptur Tall",
    "type": "Fruit",
    "scientific_name": "Cocos nucifera",
    "source": "Seedling",
    "days_to_maturity": 2555,
    "height_cm": 2000,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "5.2-8.0",
    "soil_amendment": "FYM + salt",
    "sow_method": "Seedling",
    "spacing_cm": 700,
    "germination_days": 0,
    "growing_method": "Ground",
    "growing_notes": "Requires open ground. Karnataka's Tiptur Tall is an iconic commercial variety.",
    "care_notes": "Add NaCl for better yield.",
    "harvest_season": "Year-round",
    "yield_unit": "nuts",
    "common_pests": "Rhinoceros beetle",
    "fertilizer": "NPK + micronutrients annually"
  },
  {
    "name": "Ridge Gourd",
    "variety": "Pusa Nasdar",
    "type": "Vegetable",
    "scientific_name": "Luffa acutangula",
    "source": "Seeds",
    "days_to_maturity": 60,
    "height_cm": 300,
    "water_need": "High",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 90,
    "germination_days": 5,
    "growing_method": "Trellis",
    "growing_notes": "Vertical trellis or pergola crop. Excellent for terrace pergolas or compound wall trellis.",
    "care_notes": "Train on trellis. Harvest young for eating.",
    "harvest_season": "June-September",
    "yield_unit": "fruits",
    "common_pests": "Downy mildew",
    "fertilizer": "Compost + potash"
  },
  {
    "name": "Bitter Gourd",
    "variety": "Arka Harit",
    "type": "Vegetable",
    "scientific_name": "Momordica charantia",
    "source": "Seeds",
    "days_to_maturity": 65,
    "height_cm": 300,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "6.0-6.7",
    "soil_amendment": "FYM",
    "sow_method": "Direct sowing",
    "spacing_cm": 90,
    "germination_days": 6,
    "growing_method": "Trellis",
    "growing_notes": "Classic trellis crop. Grow over gates, fences, or pergolas for dual function of shade and food.",
    "care_notes": "Trellis required. Harvest green.",
    "harvest_season": "June-October",
    "yield_unit": "fruits",
    "common_pests": "Fruit fly, downy mildew",
    "fertilizer": "NPK at flowering"
  },
  {
    "name": "Bottle Gourd",
    "variety": "Pusa Summer Prolific",
    "type": "Vegetable",
    "scientific_name": "Lagenaria siceraria",
    "source": "Seeds",
    "days_to_maturity": 60,
    "height_cm": 400,
    "water_need": "High",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 150,
    "germination_days": 5,
    "growing_method": "Trellis",
    "growing_notes": "Heavy fruiting climber — needs strong iron or bamboo trellis. Common in Karnataka terrace gardens.",
    "care_notes": "Harvest at young stage.",
    "harvest_season": "June-September",
    "yield_unit": "fruits",
    "common_pests": "Powdery mildew",
    "fertilizer": "FYM + potash"
  },
  {
    "name": "French Beans",
    "variety": "Contender",
    "type": "Vegetable",
    "scientific_name": "Phaseolus vulgaris",
    "source": "Seeds",
    "days_to_maturity": 55,
    "height_cm": 50,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 30,
    "germination_days": 5,
    "growing_method": "Both",
    "growing_notes": "Bush variety suits containers (12-inch) or ground rows. No staking needed.",
    "care_notes": "Nitrogen-fixing. Good companion plant.",
    "harvest_season": "Nov-Feb",
    "yield_unit": "kg",
    "common_pests": "Bean beetle",
    "fertilizer": "Low nitrogen — fixes own"
  },
  {
    "name": "Cluster Beans",
    "variety": "Guar",
    "type": "Vegetable",
    "scientific_name": "Cyamopsis tetragonoloba",
    "source": "Seeds",
    "days_to_maturity": 75,
    "height_cm": 90,
    "water_need": "Low",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "7.0-8.5",
    "soil_amendment": "Minimal",
    "sow_method": "Direct sowing",
    "spacing_cm": 30,
    "germination_days": 4,
    "growing_method": "Ground",
    "growing_notes": "Best in open ground. Very tolerant of alkaline soils common in parts of Karnataka.",
    "care_notes": "Very drought tolerant.",
    "harvest_season": "June-September",
    "yield_unit": "kg",
    "common_pests": "Minimal",
    "fertilizer": "Minimal"
  },
  {
    "name": "Amaranth",
    "variety": "Red Amaranth",
    "type": "Vegetable",
    "scientific_name": "Amaranthus tricolor",
    "source": "Seeds",
    "days_to_maturity": 30,
    "height_cm": 60,
    "water_need": "Low",
    "sun_hours": 6,
    "soil_type": "Any",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 15,
    "germination_days": 3,
    "growing_method": "Both",
    "growing_notes": "Excellent container leafy green. Very fast and forgiving — perfect for beginner urban gardeners.",
    "care_notes": "Fast-growing. Highly heat tolerant.",
    "harvest_season": "Year-round",
    "yield_unit": "bunches",
    "common_pests": "Minimal",
    "fertilizer": "Light compost"
  },
  {
    "name": "Radish",
    "variety": "Pusa Desi",
    "type": "Vegetable",
    "scientific_name": "Raphanus sativus",
    "source": "Seeds",
    "days_to_maturity": 30,
    "height_cm": 30,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 10,
    "germination_days": 3,
    "growing_method": "Container",
    "growing_notes": "Deep containers (12-inch depth) work well. Loosen soil well before sowing.",
    "care_notes": "Sow Oct-Feb in Karnataka.",
    "harvest_season": "Nov-Feb",
    "yield_unit": "roots",
    "common_pests": "Aphids",
    "fertilizer": "Potassium-rich compost"
  },
  {
    "name": "Carrot",
    "variety": "Nantes",
    "type": "Vegetable",
    "scientific_name": "Daucus carota",
    "source": "Seeds",
    "days_to_maturity": 75,
    "height_cm": 30,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-6.8",
    "soil_amendment": "Compost (no fresh manure)",
    "sow_method": "Direct sowing",
    "spacing_cm": 8,
    "germination_days": 10,
    "growing_method": "Container",
    "growing_notes": "Deep containers (14-inch depth). Sandy, stone-free mix is essential for straight roots.",
    "care_notes": "Thin to 8cm. Cool season only.",
    "harvest_season": "Nov-Feb",
    "yield_unit": "roots",
    "common_pests": "Carrot fly",
    "fertilizer": "No nitrogen — causes forking"
  },
  {
    "name": "Onion",
    "variety": "Bellary Red",
    "type": "Vegetable",
    "scientific_name": "Allium cepa",
    "source": "Seeds/Sets",
    "days_to_maturity": 120,
    "height_cm": 40,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "FYM",
    "sow_method": "Nursery bed",
    "spacing_cm": 15,
    "germination_days": 7,
    "growing_method": "Ground",
    "growing_notes": "Best in raised ground beds. Karnataka's Bellary district is famous for this variety commercially.",
    "care_notes": "Stop watering 2 weeks before harvest.",
    "harvest_season": "March-May",
    "yield_unit": "kg",
    "common_pests": "Thrips, purple blotch",
    "fertilizer": "Potash at bulb formation"
  },
  {
    "name": "Garlic",
    "variety": "Yamuna Safed",
    "type": "Vegetable",
    "scientific_name": "Allium sativum",
    "source": "Cloves",
    "days_to_maturity": 150,
    "height_cm": 50,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "FYM",
    "sow_method": "Clove planting",
    "spacing_cm": 10,
    "germination_days": 10,
    "growing_method": "Both",
    "growing_notes": "Works well in both deep containers (12-inch) and ground rows. Plant Oct-Nov in Karnataka.",
    "care_notes": "Reduce water at bulb maturity.",
    "harvest_season": "March-April",
    "yield_unit": "kg",
    "common_pests": "Thrips",
    "fertilizer": "Sulfur-rich compost"
  },
  {
    "name": "Ginger",
    "variety": "Maran",
    "type": "Vegetable",
    "scientific_name": "Zingiber officinale",
    "source": "Rhizome",
    "days_to_maturity": 240,
    "height_cm": 100,
    "water_need": "High",
    "sun_hours": 5,
    "soil_type": "Loamy",
    "soil_ph": "5.5-6.5",
    "soil_amendment": "Compost + neem cake",
    "sow_method": "Rhizome",
    "spacing_cm": 30,
    "germination_days": 20,
    "growing_method": "Both",
    "growing_notes": "Excellent large container crop (16-inch pots). Thrives under shade — good under trees or balcony overhang.",
    "care_notes": "Shade tolerant. Mulch heavily.",
    "harvest_season": "Nov-January",
    "yield_unit": "kg",
    "common_pests": "Soft rot, rhizome fly",
    "fertilizer": "FYM + potash"
  },
  {
    "name": "Turmeric",
    "variety": "Pragati",
    "type": "Vegetable",
    "scientific_name": "Curcuma longa",
    "source": "Rhizome",
    "days_to_maturity": 270,
    "height_cm": 90,
    "water_need": "High",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "5.5-7.0",
    "soil_amendment": "FYM",
    "sow_method": "Rhizome",
    "spacing_cm": 30,
    "germination_days": 20,
    "growing_method": "Both",
    "growing_notes": "Grow in large containers or ground. Great shade-intercrop under coconut. Mulching is essential.",
    "care_notes": "Popular in Karnataka. Mulch required.",
    "harvest_season": "Jan-Feb",
    "yield_unit": "kg",
    "common_pests": "Rhizome scale",
    "fertilizer": "FYM + NPK"
  },
  {
    "name": "Capsicum",
    "variety": "Orobelle",
    "type": "Vegetable",
    "scientific_name": "Capsicum annuum",
    "source": "Nursery",
    "days_to_maturity": 80,
    "height_cm": 70,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-6.8",
    "soil_amendment": "Compost",
    "sow_method": "Nursery bed",
    "spacing_cm": 45,
    "germination_days": 10,
    "growing_method": "Container",
    "growing_notes": "Excellent terrace container crop. 12-inch pots. Use stakes. High-value crop for urban gardeners.",
    "care_notes": "Harvest green or wait for colour.",
    "harvest_season": "Nov-March",
    "yield_unit": "fruits",
    "common_pests": "Thrips, bacterial wilt",
    "fertilizer": "Potash-rich after flowering"
  },
  {
    "name": "Cucumber",
    "variety": "Poinsett 76",
    "type": "Vegetable",
    "scientific_name": "Cucumis sativus",
    "source": "Seeds",
    "days_to_maturity": 55,
    "height_cm": 200,
    "water_need": "High",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 60,
    "germination_days": 4,
    "growing_method": "Trellis",
    "growing_notes": "Vertical trellis climbing variety. Train up net or fence. Great for compact terrace spaces.",
    "care_notes": "Harvest young and often.",
    "harvest_season": "June-September",
    "yield_unit": "fruits",
    "common_pests": "Downy mildew, cucumber beetle",
    "fertilizer": "Compost + potash"
  },
  {
    "name": "Pumpkin",
    "variety": "Arka Chandan",
    "type": "Vegetable",
    "scientific_name": "Cucurbita moschata",
    "source": "Seeds",
    "days_to_maturity": 90,
    "height_cm": 300,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "FYM",
    "sow_method": "Direct sowing",
    "spacing_cm": 200,
    "germination_days": 5,
    "growing_method": "Ground",
    "growing_notes": "Needs significant open ground space. Can sprawl over compost pits.",
    "care_notes": "Hand-pollinate for better fruit set.",
    "harvest_season": "September-November",
    "yield_unit": "fruits",
    "common_pests": "Powdery mildew",
    "fertilizer": "FYM + potash"
  },
  {
    "name": "Sweet Potato",
    "variety": "Bhu Sona",
    "type": "Vegetable",
    "scientific_name": "Ipomoea batatas",
    "source": "Vine cutting",
    "days_to_maturity": 120,
    "height_cm": 30,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Sandy loam",
    "soil_ph": "5.5-6.5",
    "soil_amendment": "Compost",
    "sow_method": "Vine cutting",
    "spacing_cm": 30,
    "germination_days": 0,
    "growing_method": "Both",
    "growing_notes": "Vines trail over containers or ground. Grow bags (40L) work well. Ornamental and edible.",
    "care_notes": "Very drought tolerant.",
    "harvest_season": "Oct-Jan",
    "yield_unit": "kg",
    "common_pests": "Sweet potato weevil",
    "fertilizer": "Potash-heavy"
  },
  {
    "name": "Marigold",
    "variety": "African Tall",
    "type": "Flower",
    "scientific_name": "Tagetes erecta",
    "source": "Seeds",
    "days_to_maturity": 60,
    "height_cm": 90,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Any",
    "soil_ph": "5.8-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 30,
    "germination_days": 5,
    "growing_method": "Both",
    "growing_notes": "Border ground planting or container edges. Use as companion plant around vegetables to repel pests.",
    "care_notes": "Repels nematodes and pests.",
    "harvest_season": "Nov-March",
    "yield_unit": "flowers",
    "common_pests": "Spider mite",
    "fertilizer": "Light compost"
  },
  {
    "name": "Rose",
    "variety": "Hybrid Tea",
    "type": "Flower",
    "scientific_name": "Rosa hybrida",
    "source": "Nursery cutting",
    "days_to_maturity": 365,
    "height_cm": 150,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-6.5",
    "soil_amendment": "Compost + bone meal",
    "sow_method": "Cutting/graft",
    "spacing_cm": 90,
    "germination_days": 0,
    "growing_method": "Both",
    "growing_notes": "Large containers (18-inch) or ground beds. South-facing placement for maximum sun.",
    "care_notes": "Prune dead wood. Apply neem oil weekly.",
    "harvest_season": "Nov-Feb",
    "yield_unit": "flowers",
    "common_pests": "Aphids, black spot",
    "fertilizer": "Rose-specific NPK"
  },
  {
    "name": "Hibiscus",
    "variety": "China Rose",
    "type": "Flower",
    "scientific_name": "Hibiscus rosa-sinensis",
    "source": "Cutting",
    "days_to_maturity": 180,
    "height_cm": 200,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Stem cutting",
    "spacing_cm": 90,
    "germination_days": 0,
    "growing_method": "Both",
    "growing_notes": "Common Karnataka garden shrub. Large pots or ground. Excellent terrace privacy screen.",
    "care_notes": "Regular pruning encourages blooming.",
    "harvest_season": "Year-round",
    "yield_unit": "flowers",
    "common_pests": "Mealy bug",
    "fertilizer": "Potash-rich monthly"
  },
  {
    "name": "Jasmine",
    "variety": "Mogra",
    "type": "Flower",
    "scientific_name": "Jasminum sambac",
    "source": "Cutting",
    "days_to_maturity": 180,
    "height_cm": 200,
    "water_need": "Medium",
    "sun_hours": 7,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Stem cutting",
    "spacing_cm": 120,
    "germination_days": 0,
    "growing_method": "Both",
    "growing_notes": "Karnataka state flower. Ground or large container. Train on trellis for vertical growing.",
    "care_notes": "Prune after flowering season.",
    "harvest_season": "March-September",
    "yield_unit": "flowers",
    "common_pests": "Bud borer",
    "fertilizer": "NPK at bud initiation"
  },
  {
    "name": "Aloe Vera",
    "variety": "Barbadensis",
    "type": "Shrub",
    "scientific_name": "Aloe barbadensis miller",
    "source": "Offset",
    "days_to_maturity": 365,
    "height_cm": 60,
    "water_need": "Low",
    "sun_hours": 6,
    "soil_type": "Sandy",
    "soil_ph": "7.0-8.5",
    "soil_amendment": "Sand + compost",
    "sow_method": "Offset",
    "spacing_cm": 30,
    "germination_days": 0,
    "growing_method": "Container",
    "growing_notes": "Ideal pot plant. Terracotta pots with drainage are best. Windowsill or balcony plant.",
    "care_notes": "Do not overwater. Pot-friendly.",
    "harvest_season": "Year-round",
    "yield_unit": "leaves",
    "common_pests": "Scale insects",
    "fertilizer": "Minimal — monthly diluted compost tea"
  },
  {
    "name": "Snake Plant",
    "variety": "Laurentii",
    "type": "Shrub",
    "scientific_name": "Dracaena trifasciata",
    "source": "Division",
    "days_to_maturity": 365,
    "height_cm": 100,
    "water_need": "Low",
    "sun_hours": 3,
    "soil_type": "Sandy",
    "soil_ph": "5.5-7.5",
    "soil_amendment": "Sand",
    "sow_method": "Division",
    "spacing_cm": 30,
    "germination_days": 0,
    "growing_method": "Container",
    "growing_notes": "Indoor/outdoor container plant. Thrives in neglect. Perfect for beginners or low-light indoor spaces.",
    "care_notes": "NASA air-purifying plant. Extremely hardy.",
    "harvest_season": "N/A",
    "yield_unit": "N/A",
    "common_pests": "Root rot if overwatered",
    "fertilizer": "Once in 6 months"
  },
  {
    "name": "Money Plant",
    "variety": "Golden Pothos",
    "type": "Shrub",
    "scientific_name": "Epipremnum aureum",
    "source": "Cutting",
    "days_to_maturity": 0,
    "height_cm": 200,
    "water_need": "Low",
    "sun_hours": 3,
    "soil_type": "Any",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Stem cutting",
    "spacing_cm": 30,
    "germination_days": 0,
    "growing_method": "Vertical",
    "growing_notes": "Vertical wall planter, hanging basket, or water bottle propagation. Indoor climbing plant.",
    "care_notes": "Can grow in water. Highly adaptable.",
    "harvest_season": "N/A",
    "yield_unit": "N/A",
    "common_pests": "Mealy bug",
    "fertilizer": "Monthly liquid fertilizer"
  },
  {
    "name": "Neem",
    "variety": "Local",
    "type": "Shrub",
    "scientific_name": "Azadirachta indica",
    "source": "Seeds",
    "days_to_maturity": 1825,
    "height_cm": 1500,
    "water_need": "Low",
    "sun_hours": 8,
    "soil_type": "Any",
    "soil_ph": "6.2-7.0",
    "soil_amendment": "None needed",
    "sow_method": "Seedling",
    "spacing_cm": 500,
    "germination_days": 14,
    "growing_method": "Ground",
    "growing_notes": "Open ground only. Large tree — ideal for community gardens or roadside. Leaves double as pesticide.",
    "care_notes": "Nitrogen-fixing.",
    "harvest_season": "Year-round",
    "yield_unit": "leaves/seeds",
    "common_pests": "Minimal",
    "fertilizer": "None needed"
  },
  {
    "name": "Ashwagandha",
    "variety": "WS-20",
    "type": "Herb",
    "scientific_name": "Withania somnifera",
    "source": "Seeds",
    "days_to_maturity": 180,
    "height_cm": 100,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Sandy loam",
    "soil_ph": "7.5-8.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 60,
    "germination_days": 7,
    "growing_method": "Both",
    "growing_notes": "Medicinal plant. Raised ground beds or large containers. Harvest roots — needs sufficient depth.",
    "care_notes": "Drought tolerant. Harvest roots in winter.",
    "harvest_season": "Dec-Feb",
    "yield_unit": "roots",
    "common_pests": "Minimal",
    "fertilizer": "Minimal"
  },
  {
    "name": "Brahmi",
    "variety": "Water Hyssop",
    "type": "Herb",
    "scientific_name": "Bacopa monnieri",
    "source": "Cutting",
    "days_to_maturity": 60,
    "height_cm": 20,
    "water_need": "High",
    "sun_hours": 5,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Cutting",
    "spacing_cm": 15,
    "germination_days": 0,
    "growing_method": "Container",
    "growing_notes": "Grow in water trays or near water feature. Hydroponic container works well. Shade-tolerant.",
    "care_notes": "Keep moist at all times.",
    "harvest_season": "Year-round",
    "yield_unit": "sprigs",
    "common_pests": "Leaf spot",
    "fertilizer": "Dilute liquid compost"
  },
  {
    "name": "Stevia",
    "variety": "Bertoni",
    "type": "Herb",
    "scientific_name": "Stevia rebaudiana",
    "source": "Nursery",
    "days_to_maturity": 90,
    "height_cm": 60,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "6.5-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Seedling",
    "spacing_cm": 45,
    "germination_days": 14,
    "growing_method": "Container",
    "growing_notes": "10-inch containers ideal. Kitchen garden herb — natural sweetener. Good balcony plant.",
    "care_notes": "Pinch flowers to keep leaves sweet.",
    "harvest_season": "Year-round",
    "yield_unit": "leaves",
    "common_pests": "Minimal",
    "fertilizer": "Organic compost monthly"
  },
  {
    "name": "Green Onion",
    "variety": "Scallion",
    "type": "Vegetable",
    "scientific_name": "Allium fistulosum",
    "source": "Sets or seeds",
    "days_to_maturity": 60,
    "height_cm": 40,
    "water_need": "Medium",
    "sun_hours": 6,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.0",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 8,
    "germination_days": 7,
    "growing_method": "Container",
    "growing_notes": "Perfect window box or small container crop. Regrow from kitchen scraps in water jars.",
    "care_notes": "Cut-and-come-again.",
    "harvest_season": "Year-round",
    "yield_unit": "bunches",
    "common_pests": "Thrips",
    "fertilizer": "Nitrogen-rich compost"
  },
  {
    "name": "Bougainvillea",
    "variety": "Crimson Lake",
    "type": "Flower",
    "scientific_name": "Bougainvillea spectabilis",
    "source": "Cutting",
    "days_to_maturity": 365,
    "height_cm": 400,
    "water_need": "Low",
    "sun_hours": 8,
    "soil_type": "Sandy loam",
    "soil_ph": "5.5-6.5",
    "soil_amendment": "Compost",
    "sow_method": "Stem cutting",
    "spacing_cm": 150,
    "germination_days": 0,
    "growing_method": "Vertical",
    "growing_notes": "Excellent wall or trellis climber. Train on compound walls, pergolas, or vertical supports.",
    "care_notes": "Prune aggressively for blooms.",
    "harvest_season": "Nov-March",
    "yield_unit": "bracts",
    "common_pests": "Scale insects",
    "fertilizer": "Potash-rich to promote flowering"
  },
  {
    "name": "Curry Basil",
    "variety": "Vana Tulsi",
    "type": "Herb",
    "scientific_name": "Ocimum gratissimum",
    "source": "Seeds",
    "days_to_maturity": 60,
    "height_cm": 80,
    "water_need": "Low",
    "sun_hours": 7,
    "soil_type": "Sandy loam",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 40,
    "germination_days": 7,
    "growing_method": "Both",
    "growing_notes": "Hardy shrubby plant. Ground border or large containers. Very heat-tolerant in Karnataka summers.",
    "care_notes": "Larger shrubby tulsi variety.",
    "harvest_season": "Year-round",
    "yield_unit": "sprigs",
    "common_pests": "Minimal",
    "fertilizer": "Light compost"
  },
  {
    "name": "Sunflower",
    "variety": "Russian Giant",
    "type": "Flower",
    "scientific_name": "Helianthus annuus",
    "source": "Seeds",
    "days_to_maturity": 80,
    "height_cm": 250,
    "water_need": "Medium",
    "sun_hours": 8,
    "soil_type": "Loamy",
    "soil_ph": "6.0-7.5",
    "soil_amendment": "Compost",
    "sow_method": "Direct sowing",
    "spacing_cm": 45,
    "germination_days": 5,
    "growing_method": "Both",
    "growing_notes": "Deep containers (14-inch) or ground. Stake tall varieties. Excellent pollinator attractor for gardens.",
    "care_notes": "Single stem per plant. Seeds edible.",
    "harvest_season": "March-May",
    "yield_unit": "seeds/flowers",
    "common_pests": "Birds, stem borer",
    "fertilizer": "Phosphorus-rich at flowering"
  }
];

const emojis = {
  'Tomato': '🍅', 'Tulsi': '🌿', 'Moringa': '🌳', 'Aloe Vera': '🪴',
  'Marigold': '🌼', 'Bitter Gourd': '🥒', 'Ridge Gourd': '🥒', 'Brinjal': '🍆',
  'Okra': '🥒', 'Jasmine': '🌸', 'Crossandra': '🌺', 'Curry Leaf': '🍃',
  'Coriander': '🌿', 'Fenugreek': '🌱', 'Banana': '🍌', 'Papaya': '🥭',
  'Pomegranate': '🍎', 'Hibiscus': '🌺', 'Money Plant': '🌿', 'Snake Plant': '🪴',
  'Rose': '🌹', 'Turmeric': '🫚', 'Ginger': '🫚', 'Mint': '🌿',
  'Hot Pepper': '🌶️', 'Spinach': '🥬', 'Lemon Grass': '🌾', 'Basil': '🌿',
  'Drumstick': '🌳', 'Lemon': '🍋', 'Guava': '🍐', 'Chikoo': '🥔',
  'Coconut': '🥥', 'Bottle Gourd': '🥒', 'French Beans': '🫛', 'Cluster Beans': '🫛',
  'Amaranth': '🥬', 'Radish': '🧄', 'Carrot': '🥕', 'Onion': '🧅', 'Garlic': '🧄',
  'Capsicum': '🫑', 'Cucumber': '🥒', 'Pumpkin': '🎃', 'Sweet Potato': '🍠',
  'Bougainvillea': '🌺', 'Curry Basil': '🌿', 'Sunflower': '🌻', 'Ashwagandha': '🌿',
  'Brahmi': '🌿', 'Stevia': '🌿', 'Green Onion': '🧅'
};

const processedData = rawData.map((plant, index) => {
  return {
    id: index + 1,
    name: plant.name,
    sc: plant.scientific_name,
    emoji: emojis[plant.name] || '🪴',
    cat: plant.type === 'Vegetable' ? 'Vegetables' : 
         plant.type === 'Herb' ? 'Herbs' :
         plant.type === 'Flower' ? 'Flowers' :
         plant.type === 'Fruit' ? 'Fruits' :
         plant.type === 'Shrub' ? 'Indoor' : 'Medicinal',
    diff: plant.water_need === 'Low' ? 'Easy' : plant.water_need === 'High' ? 'Hard' : 'Medium',
    water: plant.water_need === 'High' ? 'Daily' : plant.water_need === 'Medium' ? '2 days' : 'Weekly',
    sun: plant.sun_hours + 'h',
    yield: plant.days_to_maturity > 0 ? plant.days_to_maturity + 'd' : 'N/A',
    soil: plant.soil_type,
    
    // Rich details
    description: `${plant.name} (${plant.scientific_name}) is a beautiful and rewarding addition to your urban garden. Perfectly adapted to Karnataka's climate. ${plant.growing_notes}`,
    tips: [
      `Care: ${plant.care_notes}`,
      `Fertilizer: ${plant.fertilizer}`,
      `Spacing: ${plant.spacing_cm}cm, Sow Method: ${plant.sow_method}`
    ],
    pests: plant.common_pests,
    season: plant.harvest_season
  };
});

const output = `// Auto-generated from user JSON
export const plantsData = ${JSON.stringify(processedData, null, 2)};
`;

fs.writeFileSync('./src/data/plantsData.js', output);
console.log('Successfully wrote plantsData.js');
